### PR TITLE
profile added

### PR DESCRIPTION
**Pull request by u1068846**
Added the Profile and headshots

### CODE REVIEW

**Comment by alexsb** [comment]
Did you add the headshot?

**Comment by u1068846** [comment]
I did not, as I was not sure if it is needed.

**Comment by alexsb** [comment]
Yes, it's required - please add.

**Comment by u1068846** [comment]
It seems like the upload is disabled for those folders.

**Comment by alexsb** [comment]
You have to add it to your fork / pull request.

**Comment by u1068846** [comment]
Hi Alex, I added the head shots.

**Comment by alexsb** [comment]
See: 
image

Probably an incorrect reference.

**Pull request merged**
